/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projet_Structures_Donnees;

import View.Window;

public class App {
	public static void main(String[] args) throws Exception {
		Window.main(args);
	}
}
