/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projet_Structures_Donnees;

import View.BinarySpacePartitionApp;

public class App {
	public static void main(String[] args) throws Exception {
		BinarySpacePartitionApp.main(args);
	}
}
